### ISSUE TITLE
zkit - circom devkit

### ISSUE THREAD

**Issue by Arvolear** [dl-solarity/zkit#4]
`zkit` - ethers for circom.

The list of tasks and features:

- [x] Basic project design
- [x] Generation of ZK proofs
- [x] Generation of solidity verifiers
- [x] Verification of ZK proofs
- [x] Generation of witness
- [x] Support for alternative proving systems
